name: CI Deploy
on:
  workflow_dispatch:
jobs:
  swiftlint:
    name: SwiftLint
    uses: ./.github/workflows/lint.yml
  test:
    name: Testing App
    needs: swiftlint
    runs-on: [self-hosted, macOS]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Testing App
        run: exec ./.github/scripts/test_app.sh arm
  deploy:
    name: Deploying App [Prerelease]
    needs: [swiftlint, test]
    runs-on: [self-hosted, macOS]
    env:
      # set these to your scheme, archive name, and export options file
      SCHEME: "Sudoku"
      ARCHIVE_PATH: ${{ github.workspace }}/Build/${{ env.SCHEME }}.xcarchive
      EXPORT_PATH: ${{ github.workspace }}/Build
      EXPORT_OPTIONS_PLIST: ${{ github.workspace }}/Support/ExportOptions.plist
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build & Archive
        run: |
          mkdir -p Build
          xcodebuild \
            -scheme "${SCHEME}" \
            -archivePath "${ARCHIVE_PATH}" \
            -sdk iphoneos \
            archive
      - name: Export .ipa
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath "${ARCHIVE_PATH}" \
            -exportOptionsPlist "${EXPORT_OPTIONS_PLIST}" \
            -exportPath "${EXPORT_PATH}"
      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v3
        with:
          name: prerelease-ipa
          path: Build/*.ipa
